// <auto-generated />
namespace GlammyStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateslidebrand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateslidebrand));
        
        string IMigrationMetadata.Id
        {
            get { return "201706040241269_update-slide-brand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
